#!/usr/bin/env python3
# Companion template from The Last Mile. Modify freely and use at work, no attribution needed.
"""Build a sample decision trail database (20 decisions, sample data from the book's Anchor & Helm case) and run the override weekly report query (Template 17.2)."""
import argparse
import pathlib
import sqlite3
from datetime import datetime, timedelta

HERE = pathlib.Path(__file__).parent

# (category, decision, reason_code, reason_note), override 7/20, "other" code 2/7
ROWS = (
    [("missing documents", "accept", None, None)] * 6
    + [("missing documents", "override", "info_outdated", "Registration copy was already collected offline"),
       ("missing documents", "override", "other", "Customer changed their mind, no longer needs the document")]
    + [("priority", "accept", None, None)] * 4
    + [("priority", "override", "priority_differs", None),
       ("priority", "override", "priority_differs", None),
       ("priority", "override", "handled_offline", "Already chased by phone, action happened outside the system")]
    + [("risk signal", "accept", None, None)] * 3
    + [("risk signal", "override", "risk_differs", "Newly registered repair shop, not on the list yet"),
       ("risk signal", "override", "other", "Survey team already confirmed on site")]
)
TEXT = {"missing documents": ("Chase missing documents: copy of the vehicle registration", "Missing-document list generated by email extraction"),
        "priority": ("Suggest handling as priority, follow up today", "In queue 4 business days, above the median for its category"),
        "risk signal": ("Escalate to manual review: possible high risk", "Matched a repair-shop watch list rule")}


def main():
    ap = argparse.ArgumentParser(
        description="Build 20 sample decision trail rows and print the override weekly report (Template 17)")
    ap.add_argument("--db", default=":memory:",
                    help="SQLite file path (default is an in-memory database, discarded when the run ends)")
    args = ap.parse_args()

    con = sqlite3.connect(args.db)
    con.executescript((HERE / "schema.sql").read_text(encoding="utf-8"))
    now = datetime.now()
    for i, (cat, dec, code, note) in enumerate(ROWS):
        t = now - timedelta(hours=3 * i + 1)  # all fall within the last week
        sugg, why = TEXT[cat]
        con.execute(
            "INSERT INTO suggestions VALUES (?,?,?,?,?,?,?,?)",
            (f"s-{i:03d}", f"AH-2026-{100 + i}",
             f"snapshot://AH-2026-{100 + i}@{t:%Y%m%d}",
             "rules v12 / model 2026-05 / prompt v5", sugg, why, cat,
             (t - timedelta(hours=1)).isoformat(sep=" ", timespec="seconds")))
        con.execute(
            "INSERT INTO decisions VALUES (?,?,?,?,?,?,?)",
            (f"d-{i:03d}", f"s-{i:03d}", dec, code, note, "Linda Marsh",
             t.isoformat(sep=" ", timespec="seconds")))
    con.commit()

    report = (HERE / "weekly-override-report.sql").read_text(encoding="utf-8")
    for chunk in report.split(";"):
        if "SELECT" not in chunk.upper():
            continue
        titles = [ln for ln in chunk.splitlines() if ln.startswith("-- ")]
        print("\n== " + (titles[-1][3:] if titles else "") + " ==")
        cur = con.execute(chunk)
        print(" | ".join(c[0] for c in cur.description))
        for row in cur:
            print(" | ".join(str(v) for v in row))
    if args.db != ":memory:":
        print(f"\nSample database written to {args.db}")


if __name__ == "__main__":
    main()
